server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://120.77.203.216/gyt?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://localhost/test4?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#showSql
logging:
  level:
    com:
      example:
        mapper: debug
